name: survival
main: com.alexpsvet.Survival
version: 1.0-SNAPSHOT
api-version: '1.21'

commands:
  balance:
    description: Voir votre solde
    aliases: [bal]
  pay:
    description: Envoyer de l'argent à un joueur
    usage: /pay <joueur> <montant>
  economy:
    description: Ouvrir le menu d'économie
    aliases: [eco]
  ecoadmin:
    description: Commandes admin pour l'économie
    usage: /ecoadmin <give|take|set> <joueur> <montant>
    permission: survival.economy.admin
  clan:
    description: Menu et commandes de clan
    usage: /clan [create|invite|join|leave|kick|promote|demote|sethome|home|list|disband]
  msg:
    description: Envoyer un message privé
    aliases: [tell, whisper, w]
    usage: /msg <joueur> <message>
  r:
    description: Répondre au dernier message privé
    usage: /r <message>
  ah:
    description: Ouvrir l'Auction House
    aliases: [auctionhouse, auction]
    usage: /ah [sell|cancel]
  tpa:
    description: Demander une téléportation à un joueur
    usage: /tpa <joueur>
  tpaccept:
    description: Accepter une demande de téléportation
    usage: /tpaccept
  tpdeny:
    description: Refuser une demande de téléportation
    usage: /tpdeny
  shop:
    description: Ouvrir la boutique
    usage: /shop
  protection:
    description: Acheter des blocs de protection
    aliases: [protectionblock, pb]
    usage: /protection
  guide:
    description: Guide du serveur Survival
    aliases: [help, aide]
    usage: /guide
  waradmin:
    description: Admin commands for war arena (load,tp,test)
    usage: /waradmin <load|tp1|tp2|test>
  territory:
    description: Gérer les territoires
    aliases: [t, claim]
    usage: /territory [info|trust|untrust|claim|unclaim]
  bounty:
    description: Système de primes
    usage: /bounty
  jobs:
    description: Système de métiers
    usage: /jobs
  gamble:
    description: Jeu de pile ou face
    aliases: [coinflip, pileouface]
    usage: /gamble
  home:
    description: Menu des homes et téléportation
    usage: /home [nom]
  sethome:
    description: Définir un home
    usage: /sethome [nom]
  delhome:
    description: Supprimer un home
    usage: /delhome <nom>

permissions:
  survival.economy.admin:
    description: Accès aux commandes admin d'économie
    default: op
  survival.economy.balance.others:
    description: Voir le solde des autres joueurs
    default: op
  survival.premium.rank1:
    description: Rang VIP
    default: false
  survival.premium.rank2:
    description: Rang VIP+
    default: false
  survival.premium.rank3:
    description: Rang MVP
    default: false
  survival.admin:
    description: Accès aux commandes admin
    default: op
  survival.tpa:
    description: Utiliser les commandes de téléportation
    default: true
  survival.shop:
    description: Accès à la boutique
    default: true
  survival.bounty:
    description: Accès au système de primes
    default: true
  survival.jobs:
    description: Accès au système de métiers
    default: true
  survival.gamble:
    description: Accès au jeu de hasard
    default: true
  survival.home:
    description: Accès au système de homes
    default: true
